export const HEADER_VIEWS = {
  HOME: "HOME",
  ABOUT_US: "ABOUT_US",
  CONTACT_US: "CONTACT_US",
  RESPONSIVE: "RESPONSIVE",
};
export const LANGUAGE_OPTIONS = {
  en: "englishUSA",
};

export const APP_INITIALIZATION_ERROR_MESSAGE_TID =
  "APP_INITIALIZATION_ERROR_MESSAGE_TID";
export const APPLICATION_TITLE = "APPLICATION_TITLE";
export const INVALID_DATA = "INVALID_DATA";
export const PROCESSING = "PROCESSING";
