export const VIEW_ROUTE_SCREENS = {
  MAIN_VIEW: "MAIN_VIEW",
  LANDING_VIEW: "LANDING_VIEW",
  PRODUCTS_VIEW: "PRODUCTS_VIEW",
  PROCESSING: "PROCESSING",
};
export const RIGHT_PANEL_VIEWS = {
  STAR_VIEW_COMPONENT: "STAR_VIEW_COMPONENT",
  MOVIE_VIEW_COMPONENT: "MOVIE_VIEW_COMPONENT",
  WEDDING_VIEW_COMPONENT: "WEDDING_VIEW_COMPONENT",
};
