export const PRODUCTS_VIEW_INITIATED = "PRODUCTS_VIEW_INITIATED";
export const PRODUCTS_VIEW_DISPLAY_CATEGORY = "PRODUCTS_VIEW_DISPLAY_CATEGORY";
export const INITIATE_PRODUCTS_CATEGRORY_PANEL =
  "INITIATE_PRODUCTS_CATEGRORY_PANEL";
