export const DISPLAY_PRODUCTS_VIEW = "DISPLAY_PRODUCTS_VIEW";
export const DISPLAY_STAR_PRODUCTS_LIST = "DISPLAY_STAR_PRODUCTS_LIST";
export const DISPLAY_SELECTED_STAR_COLLECTIONS =
  "DISPLAY_SELECTED_STAR_COLLECTIONS";
